### ISSUE TITLE
Community Grant for new indexer-focused tutorial series

### ISSUE THREAD

**Issue by alex-pakalniskis** [IndexerDAO/IndexerDAO#85]
Live workshops + written and video tutorials to help train the next generation of indexers and web3 node operators. 

## Proof-of-concept syllabus
| Unit | Lesson |  Title |
| --- | --- | --- |
| 1 | 1 | Introduction to Linux |
| 1 | 2 | Getting started with Ethereum clients |
| 1 | 3 | Selecting appropriate hardware |
| 1 | 4 | Lab: Sync a blockchain node |

## Previous grant proposals
* Code Along with Alex Grant Application: https://forum.graphadvocates.com/t/grant-proposal-code-along-with-alex/273
* Rust Office Hours Resources Grant Application: https://forum.graphadvocates.com/t/grant-proposal-rust-office-hours-resources/502

**Comment by alex-pakalniskis** [comment]
@Web3Slimchance and @reinasun

does anything look massively wrong in the prototype syllabus?

thanks :smile:

**Comment by reinasun** [comment]
This looks amazing! and very helpful to new indexing-community members. I wonder if, perhaps, we can do an intro video outlining the following information:

•	Our mission and vision. What information to expect and when. Where to go with questions or if unable to make a specific training. quick reference sheets to related links
•	Indexing and how it relates to The Graph community (subgraph dev, curating, delegating) 
•	Use cases and how indexing expands the web3 ecosystem
•	The importance of collaboration and connection for long-term success
•	Perhaps an ending video with ways to stay connected, work through issues, and contribute

Also, do you think it would be useful to overview our use case scenario? To help people understand the choices that were made and why, monetary considerations/planning, and how to deal with the unexpected. 

One more idea: Prizes, NFTs, badges, GRT, mentions to the most engaged to be added to social media may help with continued engagement

**Comment by alex-pakalniskis** [comment]
Great ideas about the intro/outro videos to share our mission/vision, emphasize importance of collaboration, and tips for getting connected and contributing.

I think the reward idea is great too. Would be cool if we could do something like Kudos: https://mintkudos.xyz/

**Comment by reinasun** [comment]
mintkudos! love that idea

**Comment by alex-pakalniskis** [comment]
## Project Name*
Indexing 101

## Please provide a description of your project*
Ten free and open-source lessons, videos, and live workshops to foster a small learning community around indexer fundamentals. 

Participants will be rewarded with a [POAP](https://poap.xyz/) NFT upon demonstrating their mastery of indexing fundamentals through session participation, quizzes, and assignments. 

Tutorials will be released every other Indexer Office Hours throughout Q2 and Q3 of 2023.




Unit | Lesson | Title | Topics
-- | -- | -- | --
1 | 1 | Introduction to Linux | Command line basics, git, user management, systemd, firewalls
1 | 2 | Getting started with Ethereum clients | Nethermind and Erigon on systemd, Hardware factors to consider
1 | 3 | Lab 1: Sync a blockchain node | Sync an RPC node with systemd: Gnosis, Nethermind on a Hetzner server
2 | 1 | Intro to indexer operations | Wallets (hot vs cold, indexer vs operator), Multisigs, Faucets, Network Registration
2 | 2 | Getting started with containers | Docker, docker-compose, Kubernetes (briefly), Helm (briefly)
2 | 3 | Lab 2: Configure your indexing stack | Deploy The Graph indexing stack and connect to your Gnosis RPC node
3 | 1 | Intro to indexing strategy | Basic overview of subgraphs and market conditions
3 | 2 | Getting started with allocation management | Opening and closing allocations, Troubeshooting
3 | 3 | Lab 3: Index and allocate on a subgraph | Index and allocate on a Gnosis subgraph
4 | 1 | What's next? | Mainnet, Multiple subgraphs, Kubernetes, Multi-chain








## Are you applying as a team or individual?*
Team

## What type of grant are you pursuing?*
Project (one-off)

## Please select the category your project best fits into*
Education

## Please select who you think will benefit from your project?*
Indexers


## How much funding are you looking for? (USD)*
$10000


## Have you applied for (or already received) funding from somewhere else?*
No


## What's your vision for how your project will impact The Graph and/or web3?*
Our long-term vision is to become a DevOps talent incubator for The Graph and broader web3 ecosystem. We hope to support aspiring and active indexers with on-going education and project-based learning opportunities to ensure best practices are shared throughout the community. 


## What can you share about any past work that is relevant to this grant?*
IndexerDAO has been supporting the indexing community during MIPs with server setup guides (https://indexerdao.github.io/server-setup/) and QA testing (Launchpad, Graphcast, RPC node setup guides). We've held two community support workshops earlier in MIPs and are planning more. 


## Why are you interested in contributing to The Graph and/or web3?*
Our DAO is comprised of The Graph protocol contributors from a variety of backgrounds. We are passionate about decentralization, building a more diverse indexing talent pool, and fostering a community of collaboration and knowledge sharing. In applying for this grant we hope to accelerate our contributions to the protocol (and web3) by enabling our team to dedicate more time to developing educational content for the growing multi-chain indexing community.  


## Please provide the ETH Address which would receive the grant funding, if approved*
0x223260f3Ca014AdC40C98d50D5C4178657D53E26

**Comment by reinasun** [comment]
Helpful info perhaps to add to meeting invites

**Free New Indexer 10 Session Workshop**

About this event:
This virtual workshop will run over 10 sessions to help you start your path to indexing with the graph. All content is in English and it is totally free. 

How long are the sessions?
Each session is 2 hours with 1.5 of content and 0.5 hours of Q&A

Why be an Indexer with The Graph?
An Indexer provides the Web3 community with fast, reliable, and secure data. In return, active Indexer can provide services and earn income from the network, proportional to the amount of work they perform and their GRT stake.

What is a GRT stake?
To ensure economic security of The Graph Network and the integrity of data being queried, participants stake and use Graph Tokens (GRT). GRT is a work token that is an ERC-20 on the Ethereum blockchain, used to allocate resources in the network. 

Who can participate in this workshop?
This Workshop is designed for anyone who wants to learn about The Graph and Indexing. 

What will you learn?
You will learn about the Graph, it’s ecosystem, fundamentals, and the components to become a successful indexer.

How does Indexing fit into The Graph ecosystem?
The Graph Network consists of Indexers, Curators and Delegators that provide services to the network, and serve data to Web3 applications. Consumers use the applications and consume the data.

What are the main indexing components?
The Indexer Software Stack
Hardware & Storage
Blockchain nodes
Orchestration 
Operation
Security 
Tools

What are fundamentals skills to becoming an Indexer?
Community Connection: Discord Server, Github, Indexer OH
Marketing: Indexing Strategy, subgraphs, market conditions, delegators, curators
Linux: command line basics, system
Tool Management:  
Software: Rust, docker, kubernetes, helm
Managing Blockchain Nodes: RPC, The Graph Node, ETH Client
Hardware:/Storage: Small, Standard, Medium, Large
Operations: Allocation management, Monitoring, Alerting, IR, Backups
Security: Operator wallet, firewall, ports 
Cloud: Heztner (side note: google cloud, aws, ms azure, Alibaba)

**Comment by alex-pakalniskis** [comment]
Hey doxe01.eth and Lorena,

I'll answer both of your questions in this response as there is some overlap.

We, IndexerDAO, are planning on releasing this educational content over quarter 2 and 3 of 2023 (April 1 through September 30). This is a team effort (as indicated in the grant application) and the project will be worked on by 2-4 IndexerDAO members. I submitted this application as a member of IndexerDAO.  

All learning materials will be freely available to the community on GitHub and YouTube, with lessons released as they are completed so the community does not need to wait until we've finished everything. Anyone will be able to watch and follow along with tutorials as soon as they are published. We plan on holding synchronous workshops for interested community members but also leave open the option for asynchronous participation (especially since content may be translated later on and new community members will likely join).

Currently we do not have plans to localize our content but are very open to collaborations with Advocate Text Translators once our English content is produced. We can certainly add subtitles/captions to our video recordings to help facilitate localization by other Advocates. We are investigating GitBook as the platform to share our educational content: https://docs.gitbook.com/. This is the same platform utilized by the Graph Advocates (https://docs.graphadvocates.com/) and StreamingFast (https://substreams.streamingfast.io/). See GitBook Internationalization for more: https://docs.gitbook.com/tour/internationalization, https://docs.gitbook.com/getting-started/publishing/collection-publishing


$10000 USD for 10 lessons, with each requiring:
* Research content (3-4 hours)
* Write scripts, code, and text explanations (4-5 hours)
* Host a live workshop (1-2 hours)
* Record a video and add captions (2-3 hours)
* Maintain lesson and video content + code repositories to reflect changes to The Graph protocol (1-2 hours)


11-16 hours of work per guide

110-160 hours for 10 guides @ 10000 USD = $62.5 to $90/hr 

* 2 senior Indexers who have been running mainnet Indexers for several years. 
    * They are also running validators across multiple networks
* 2 junior Indexers with web2 and web3 engineering experience
* 4 other members with system administration, application development, technical writing, web3, and workshop hosting experience

**Comment by alex-pakalniskis** [comment]
@reinasun and @Web3Slimchance could you share a short blurb about your relevant experience? 

I'll add your response to the above comment in response to a forum comment.

Likewise, I'd appreciate your input on the response I drafted.

**Comment by reinasun** [comment]
Also, what are thoughts on polling the community for input on their indexing wants/needs?

**Comment by reinasun** [comment]
Highly technical environment for the last 10+years, ranging from system admin, cloud security engineer, system auditor, and emerging technology project management/integration. Focused on web3 for the last 2+years.  Experience is here: www.linkedin.com/in/shannonreinasol

**Comment by alex-pakalniskis** [comment]
> Also, what are thoughts on polling the community for input on their indexing wants/needs?

@reinasun I think this is a great idea but I'd rather wait until we get this proof-of-concept tutorial series up and running before polling for feedback.

I think that getting this content out is important and we can always take feedback to create additional content, i.e. different chains and Ethereum clients, different server provider, etc.

Also it might be easier for the community to identify/recognize their wants when they can compare against our tutorials.

Thoughts?

**Comment by reinasun** [comment]
I agree and It's a great idea to create content as a foundation, then to use surveys or feedback to adjust if needed. One of the best things to do is to understand the audience

**Comment by alex-pakalniskis** [comment]
17th morning (Pacific time) co-working session

**Comment by alex-pakalniskis** [comment]
@Cuervodelmar could you walk through the three pages under this section? https://docs.indexerdao.com/indexing-101/linux-and-ethereum-clients

here are some leading questions/comments for your knowledge:
* Would the intro the linux lesson benefit from a shorter, more focused lesson followed by a longer appendix?
    * free linux cli environment: https://killercoda.com/playgrounds/scenario/ubuntu
* Lesson 2 setting up CL section looks like its currently macOS focused (and needs some love), so I think we'll need to replace with Linux commands and iinstructions (i.e. `brew` stuff unless I'm way wrong)
* Once you get to the lab reach out and we can get you some credentials for testing.

**Comment by alex-pakalniskis** [comment]
@idalithb are you interested in supporting this project by contributing to a lesson?

Here's the lesson I had in mind (its related to content you've been reading on your own).

Title: Intro to indexer operations 

Contents: Wallets (hot vs cold, indexer vs operator), Multisigs, Faucets, Network Registration

Let me know if you're game and we can set up a sesh.

**Comment by CuervoDelMar** [comment]
@alex-pakalniskis 

- I'll begin going through the three pages. I can certainly ideate on how to structure the information. Appreciate the link to the ubuntu CLI
- For Lesson 2; I'm looking at this [portion specifically](https://docs.indexerdao.com/indexing-101/linux-and-ethereum-clients/getting-started-with-ethereum-clients#cl-client) correct? Or the overall [Set Up](https://docs.indexerdao.com/indexing-101/linux-and-ethereum-clients/getting-started-with-ethereum-clients#setting-up-the-client)
- Ex. Install Nimbus client `brew install --cask nimbus`
- I'll reach out once I have gone through the first two points to get lab credentials.

**Comment by alex-pakalniskis** [comment]
@CuervoDelMar here's another link to a different CLI tutorial I'm creating: https://gisc605.alexpakalniskis.com/lab-exercises/1-introduction-to-the-command-line
Let me know if this sort of flow is preferable or not for Indexing 101 Lesson 1 (Intro to Linux).

For Lesson 2 please read through the whole thing. I just wanted to add a disclaimer in case it doesn't yet make total sense (sorry that wasn't more clear).

**Comment by CuervoDelMar** [comment]
@alex-pakalniskis for the intro page I think it would benefit from breaking them into more concise lessons. Just from a context of coming in cold to the world of blockchain.

Reading through the lesson it's pretty straight forward but I'm hitting a bit of a snag with the last part for installing Ethereum `brew install ethereum --devel` and receive the following:
`Error: invalid option: --devel`

Other than that maybe a disclaimer before the installation steps mentions that some of these require homebrew installed via linux to help facilitate the CL and EL clients. Like "Some of these component require installation of [Homebrew](https://brew.sh/) "  just for like the total newbies .

**Comment by alex-pakalniskis** [comment]
# TODO 
- [ ] Get server access for Irving to test Lab 1
- [ ] Update Lesson 1 to be more concise and migrate current content to appendix
- [ ] Update Lesson 2 from macOS- to Ubuntu-based instructions
- [ ] Review/merge Ida's edits

**Comment by reinasun** [comment]
Hi all,

I'm having a difficult time connecting on Discord. Is it possible to find
me on Discord and add me back on server?

I've attached my discord info.

Thank you,
Shannon
[image: Screenshot 2023-07-13 at 11.46.33 AM.png]

**Comment by CuervoDelMar** [comment]
@alex-pakalniskis got to Step 8 of the SSH part (unsure where I'll be pulling the SSH key from to paste. Also I might've done it wrong since I tried to use VIM to modify th efile). Also wanted to share two screen shots from the other steps in Termius.
1) Install build-essential, ran it as is but just a head's up that this comes up.
<img width="780" alt="1" src="https://github.com/IndexerDAO/IndexerDAO/assets/83199125/dbe7b5f6-17a6-45ef-a05e-3addba0c2246">
2) After creating dev user. Should we leave these blank? Or do we want our learners to set something specific up. I was able to get through by leaving these blank
<img width="505" alt="2" src="https://github.com/IndexerDAO/IndexerDAO/assets/83199125/35b5073a-c851-4925-a49b-b4aec9a507d5">

**Comment by alex-pakalniskis** [comment]
hey @reinasun 

Your previous comment is formatted weird on my end: https://github.com/IndexerDAO/IndexerDAO/issues/85#issuecomment-1634730384

Could you reshare your Discord username and we can re-add you.

**Comment by reinasun** [comment]
Hi,

This was lost in my email. Sorry for the delay. my Discord user name is
channon9821.

Thank you,
Shannon

**Comment by alex-pakalniskis** [comment]
@reinasun I can't directly add you since it doesn't look like we're "friends" on Discord. Can you join via this link? (good for 7 days): https://discord.gg/yednt2T7

**Comment by reinasun** [comment]
[image: Screenshot 2023-08-03 at 12.09.30 PM.png]Hi Alex. unfortunately the
invite expired. it's only been 6 hours

**Comment by alex-pakalniskis** [comment]
@reinasun https://discord.gg/yednt2T7
